import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en">
    //   <body
    //     className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    //   >
    //     {children}
    //   </body>
    // </html>

    <html lang="es">
      <body className={styles.body}>
        <header className={styles.header}>
          <h1 className={styles.hotelpremier}>Hotel Premier</h1>
          
        </header>

          {/* <div className={styles.navbar}>
            <nav>
            <a href="/alta-huesped">Alta huésped</a>
            <a href="/reservas">Reservas</a>
          </nav>
          </div> */}


        <main className={styles.main}>{children}</main>

        <footer className={styles.footer}>
          © 2025 Hotel Premier - Todos los derechos reservados
        </footer>
      </body>
    </html>
  

  );
}
